sonar.projectKey=pai-lissajous-mvc
sonar.projectName=PAI Práctica 11 - Curvas de Lissajous
sonar.projectVersion=1.0

sonar.sources=src/exercises/home-work
sonar.exclusions=**/node_modules/**,**/dist/**,**/doc/**,**/uml/**,**/*.html,**/*.css,**/*.scss

sonar.host.url=http://localhost:9000

sonar.login=${env.SONAR_TOKEN}